ALTER TABLE diet_foods ADD COLUMN IF NOT EXISTS carbs_g INT DEFAULT 0;
ALTER TABLE diet_foods ADD COLUMN IF NOT EXISTS fat_g INT DEFAULT 0;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS carbs_goal INT DEFAULT 0;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS fat_goal INT DEFAULT 0;
